#!/usr/bin/env python3
"""Queue a manual homebrew release for the next digest without touching manual_releases.json.

    python add_release.py https://github.com/owner/repo [more URLs]   # latest release
    python add_release.py https://github.com/owner/repo/releases/tag/v1.2 --description "..."
    python add_release.py --status

Rows go to manual_inbox.json in the Gist, which only this script writes. Every server cycle
copies new inbox rows into manual_releases.json (sync_gist_state.absorb_inbox), so nothing here
races the server's uploads. A row leaves the inbox once the digest has published it.
"""
import argparse
import json
import sys
import urllib.parse
import urllib.request
import uuid
from datetime import datetime, timezone

import sync_gist_state as sgs
from collect_custom_releases import analyze_repo_with_gemini, fetch_latest_release

MANUAL = "manual_releases.json"


def github(path: str, token: str):
    req = urllib.request.Request(f"https://api.github.com/{path}", headers={
        "Accept": "application/vnd.github.v3+json", "User-Agent": "RuTracker-Bot-Collector",
        **({"Authorization": f"token {token}"} if token else {})})
    with urllib.request.urlopen(req) as r:
        return json.loads(r.read().decode())


def read_gist(gist_id: str, token: str) -> tuple:
    req = urllib.request.Request(f"https://api.github.com/gists/{gist_id}", headers=sgs.get_gist_headers(token))
    with urllib.request.urlopen(req) as r:
        files = json.loads(r.read().decode())["files"]
    rows = lambda name: json.loads(sgs.gist_file_text(files[name], token) or "[]") if name in files else []
    return rows(MANUAL), rows(sgs.INBOX_FILE)


def write_inbox(gist_id: str, token: str, inbox: list):
    payload = json.dumps({"files": {sgs.INBOX_FILE: {"content": json.dumps(inbox, ensure_ascii=False, indent=2)}}})
    req = urllib.request.Request(f"https://api.github.com/gists/{gist_id}", data=payload.encode("utf-8"),
                                 headers=sgs.get_gist_headers(token), method="PATCH")
    urllib.request.urlopen(req).close()


def build_row(url: str, args, token: str) -> dict:
    parts = urllib.parse.urlparse(url).path.strip("/").split("/")
    if len(parts) < 2:
        raise ValueError(f"not a GitHub repository URL: {url}")
    owner, repo = parts[0], parts[1]
    info = github(f"repos/{owner}/{repo}", token)
    if len(parts) >= 5 and parts[2:4] == ["releases", "tag"]:
        release = github(f"repos/{owner}/{repo}/releases/tags/{urllib.parse.quote(parts[4])}", token)
    else:
        release = fetch_latest_release(owner, repo, token)
    if release:
        version, release_url, date = release["tag_name"], release["html_url"], release["published_at"]
    else:  # no tagged releases: announce the latest commit, as was done for noJMe
        commit = github(f"repos/{owner}/{repo}/commits?per_page=1", token)[0]
        version, release_url, date = f"dev ({commit['sha'][:7]})", info["html_url"], commit["commit"]["committer"]["date"]

    ai = {} if (args.name and args.description) else analyze_repo_with_gemini(
        repo, info.get("description"), info.get("topics", []), owner)
    return {
        "type": "homebrew",
        "platform": args.platform,
        "app_name": args.name or f"{ai.get('app_name') or repo} ({owner})",
        "version": args.version or version,
        "release_url": release_url,
        "description": args.description or str(ai.get("description") or f"Новий реліз {repo} для Nintendo Switch."),
        "is_new": not args.update,
        "date": date,
        "processed": False,
        "inbox_id": uuid.uuid4().hex,
        "added_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
    }


def status(manual: list, inbox: list):
    by_id = {m.get("inbox_id"): m for m in manual if m.get("inbox_id")}
    if not inbox:
        print("Inbox is empty.")
    for row in inbox:
        m = by_id.get(row["inbox_id"])
        state = "waiting for the next server cycle" if m is None else ("published" if m.get("processed") else "queued for the next digest")
        print(f"{row['app_name']} {row['version']}: {state}")
    pending = [m for m in manual if not m.get("processed")]
    print(f"\nmanual_releases.json: {len(pending)} pending of {len(manual)}")
    for m in pending:
        print(f"  {m.get('app_name') or m.get('title')} {m.get('version', '')}")


def main():
    try:
        sys.stdout.reconfigure(encoding="utf-8")
    except AttributeError:
        pass
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("urls", nargs="*", help="GitHub repository or release-tag URLs")
    p.add_argument("--description", help="Ukrainian description (default: generated by the LLM)")
    p.add_argument("--name", help="app name, e.g. 'noJMe (corax89)' (default: generated)")
    p.add_argument("--version", help="override the detected version")
    p.add_argument("--platform", default="Switch")
    p.add_argument("--update", action="store_true", help="announce as an update, not a new app")
    p.add_argument("--dry-run", action="store_true", help="print the rows without writing the Gist")
    p.add_argument("--status", action="store_true", help="show what is queued and what was published")
    args = p.parse_args()
    if not args.urls and not args.status:
        p.error("give at least one URL or --status")
    if len(args.urls) > 1 and (args.description or args.name or args.version):
        p.error("--description/--name/--version apply to a single URL")

    gist_id, token, _ = sgs.resolve_gist_credentials()
    if not gist_id or not token:
        sys.exit("GIST_ID / GIST_TOKEN are not set (config/local_settings.json).")
    manual, inbox = read_gist(gist_id, token)
    if args.status:
        return status(manual, inbox)

    taken = {(r.get("release_url"), r.get("version")) for r in manual + inbox}
    added = []
    for url in args.urls:
        row = build_row(url, args, token)
        if (row["release_url"], row["version"]) in taken:
            print(f"Skipped {row['app_name']} {row['version']}: already queued or published.")
            continue
        taken.add((row["release_url"], row["version"]))
        added.append(row)
        print(json.dumps(row, ensure_ascii=False, indent=2))
    if not added or args.dry_run:
        return

    # Published rows leave the inbox; queued ones stay so the server can re-take a row an upload lost.
    published = {m.get("inbox_id") for m in manual if m.get("processed") and m.get("inbox_id")}
    write_inbox(gist_id, token, [r for r in inbox if r["inbox_id"] not in published] + added)
    print(f"\nAdded {len(added)} release(s) to {sgs.INBOX_FILE}; the next server cycle queues them.")


if __name__ == "__main__":
    main()
