"""Curated catalog of top popular, AAA, and critically acclaimed games for Nintendo Switch."""

from typing import List

POPULAR_SWITCH_GAMES: List[str] = [
    # --- AAA & Major Franchises ---
    "Persona 5 Royal",
    "Persona 4 Golden",
    "Persona 3 Portable",
    "Persona 5 Strikers",
    "Persona 5 Tactica",
    "Shin Megami Tensei V",
    "Shin Megami Tensei V: Vengeance",
    "Shin Megami Tensei III Nocturne HD",
    "Wolfenstein II: The New Colossus",
    "Wolfenstein: Youngblood",
    "DOOM Eternal",
    "DOOM",
    "DOOM 64",
    "Quake",
    "Quake II",
    "The Witcher 3: Wild Hunt",
    "The Elder Scrolls V: Skyrim",
    "Dark Souls: Remastered",
    "NieR:Automata The End of YoRHa Edition",
    "Monster Hunter Rise",
    "Monster Hunter Generations Ultimate",
    "Monster Hunter Stories 2: Wings of Ruin",
    "Monster Hunter Stories",
    "BioShock: The Collection",
    "BioShock Remastered",
    "BioShock 2 Remastered",
    "BioShock Infinite",
    "Borderlands Legendary Collection",
    "Borderlands: Game of the Year Edition",
    "Borderlands: The Handsome Collection",
    "Borderlands 3",
    "Tales from the Borderlands",
    "Diablo III: Eternal Collection",
    "Diablo II: Resurrected",
    "Diablo Prime Evil Collection",
    "Resident Evil 4",
    "Resident Evil",
    "Resident Evil 0",
    "Resident Evil 5",
    "Resident Evil 6",
    "Resident Evil Revelations",
    "Resident Evil Revelations 2",
    "Hogwarts Legacy",
    "Batman: Arkham Trilogy",
    "Red Dead Redemption",
    "Grand Theft Auto: The Trilogy",
    "Mortal Kombat 11",
    "Mortal Kombat 1",
    "Crash Bandicoot N. Sane Trilogy",
    "Crash Bandicoot 4: It's About Time",
    "Crash Team Racing Nitro-Fueled",
    "Spyro Reignited Trilogy",
    "Sonic Frontiers",
    "Sonic Superstars",
    "Sonic Mania",
    "Sonic Colors: Ultimate",
    "Sonic x Shadow Generations",
    "Bayonetta",
    "Bayonetta 2",
    "Bayonetta 3",
    "Bayonetta Origins",
    "No Man's Sky",
    "Civilization VI",
    "Star Wars: Knights of the Old Republic",
    "Star Wars: Knights of the Old Republic II",
    "Star Wars: The Force Unleashed",
    "Star Wars: Republic Commando",
    "Star Wars Jedi Knight: Jedi Academy",
    "Star Wars Jedi Knight II: Jedi Outcast",
    "Star Wars: Episode I Racer",
    "Metro 2033 Redux",
    "Metro: Last Light Redux",
    "Dying Light: Definitive Edition",
    "Alien: Isolation",
    "Crysis Remastered",
    "Crysis 2 Remastered",
    "Crysis 3 Remastered",
    "Crysis Remastered Trilogy",
    "Divinity: Original Sin 2",
    "Pillars of Eternity: Complete Edition",
    "Valkyria Chronicles",
    "Valkyria Chronicles 4",
    "Catherine: Full Body",
    "Tales of Vesperia: Definitive Edition",
    "Tales of Symphonia Remastered",
    "Dragon Quest XI S: Echoes of an Elusive Age",
    "Dragon Quest Monsters: The Dark Prince",
    "Final Fantasy VII",
    "Final Fantasy VIII Remastered",
    "Final Fantasy IX",
    "Final Fantasy X/X-2 HD Remaster",
    "Final Fantasy XII The Zodiac Age",
    "Crisis Core -Final Fantasy VII- Reunion",
    "Kingdom Come: Deliverance",
    "Saints Row: The Third - The Full Package",
    "Saints Row IV: Re-Elected",
    "Assassin's Creed: The Rebel Collection",
    "Assassin's Creed The Ezio Collection",
    "Assassin's Creed III: Remastered",
    "Need for Speed Hot Pursuit Remastered",
    "Burnout Paradise Remastered",
    "Tony Hawk's Pro Skater 1 + 2",
    "Rayman Legends: Definitive Edition",
    "Prince of Persia: The Lost Crown",
    "It Takes Two",
    "Unravel Two",
    "Mario + Rabbids Kingdom Battle",
    "Mario + Rabbids Sparks of Hope",
    "Immortals Fenyx Rising",
    "Just Dance 2024 Edition",
    "Lego Star Wars: The Skywalker Saga",
    "Lego Marvel Super Heroes",
    "Lego DC Super-Villains",
    "Lego City Undercover",
    "Lego Harry Potter Collection",
    "Lego Jurassic World",
    "Lego The Incredibles",
    "Mega Man 11",
    "Mega Man Legacy Collection",
    "Mega Man X Legacy Collection",
    "Mega Man Zero/ZX Legacy Collection",
    "Castlevania Advance Collection",
    "Castlevania Dominus Collection",
    "Castlevania Anniversary Collection",
    "Contra Anniversary Collection",
    "Streets of Rage 4",
    "Teenage Mutant Ninja Turtles: Shredder's Revenge",
    "Teenage Mutant Ninja Turtles: The Cowabunga Collection",
    "Capcom Beat 'Em Up Bundle",
    "Capcom Arcade Stadium",
    "Street Fighter 30th Anniversary Collection",
    "Ace Attorney Anthology",
    "Phoenix Wright: Ace Attorney Trilogy",
    "The Great Ace Attorney Chronicles",
    "Ghost Trick: Phantom Detective",
    "Okami HD",
    "Dragon's Dogma: Dark Arisen",
    "Onimusha: Warlords",
    "Overwatch 2",
    "Apex Legends",
    "Warframe",
    "Minecraft",
    "Minecraft Dungeons",
    "Minecraft Legends",
    "Portal: Companion Collection",
    "Portal",
    "Portal 2",
    "Cult of the Lamb",
    "Dredge",
    "Tunic",
    "Dave the Diver",
    "Balatro",
    "Sea of Stars",
    "Animal Well",
    "Cocoon",
    "Chants of Sennaar",
    "Outer Wilds",
    "Signalis",
    "Crow Country",
    "Lorelei and the Laser Eyes",

    # --- Top Acclaimed Indies & Masterpieces ---
    "Hollow Knight",
    "Hades",
    "Celeste",
    "Dead Cells",
    "Disco Elysium - The Final Cut",
    "Slay the Spire",
    "Stardew Valley",
    "Cuphead",
    "Subnautica",
    "Subnautica: Below Zero",
    "Ori and the Blind Forest",
    "Ori and the Will of the Wisps",
    "Inside",
    "Limbo",
    "Undertale",
    "Katana Zero",
    "Hotline Miami Collection",
    "Return of the Obra Dinn",
    "Shovel Knight: Treasure Trove",
    "Enter the Gungeon",
    "Risk of Rain 2",
    "Risk of Rain Returns",
    "The Messenger",
    "Death's Door",
    "Neon White",
    "Loop Hero",
    "Vampire Survivors",
    "A Short Hike",
    "Gris",
    "Spiritfarer",
    "Blasphemous",
    "Blasphemous 2",
    "Guacamelee! Super Turbo Championship Edition",
    "Guacamelee! 2",
    "Terraria",
    "Overcooked! 2",
    "Overcooked! All You Can Eat",
    "Don't Starve: Nintendo Switch Edition",
    "Don't Starve Together",
    "Broforce",
    "My Friend Pedro",
    "Superhot",
    "The Binding of Isaac: Afterbirth+",
    "Crypt of the NecroDancer",
    "Cadence of Hyrule",
    "SteamWorld Dig 2",
    "SteamWorld Heist",
    "SteamWorld Heist II",
    "SteamWorld Quest",
    "Golf Story",
    "Sports Story",
    "Eastward",
    "CrossCode",
    "Chained Echoes",
    "Inscryption",
    "Citizen Sleeper",
    "Oxenfree",
    "Oxenfree II: Lost Signals",
    "What Remains of Edith Finch",
    "Firewatch",
    "Untitled Goose Game",
    "Unpacking",
    "A Little to the Left",
    "Dorfromantik",
    "Mini Motorways",
    "Baba Is You",
    "Gorogoa",
    "Sayonara Wild Hearts",
    "Kentucky Route Zero",
    "Night in the Woods",
    "To the Moon",
    "A Hat in Time",
    "Yooka-Laylee and the Impossible Lair",
    "Bloodstained: Ritual of the Night",
    "Bloodstained: Curse of the Moon",
    "Bloodstained: Curse of the Moon 2",
    "Mark of the Ninja: Remastered",
    "Spelunky",
    "Spelunky 2",
    "Rogue Legacy 2",
    "Moonlighter",
    "Children of Morta",
    "Carrion",
    "Gungeon",
    "Slime Rancher: Plortable Edition",
    "Submerged: Hidden Depths",
    "Human: Fall Flat",
    "Gang Beasts",
    "Among Us",
]

MAJOR_PUBLISHERS: List[str] = [
    "Nintendo",
    "Capcom",
    "SEGA",
    "Ubisoft",
    "Bethesda",
    "Square Enix",
    "Electronic Arts",
    "Warner Bros",
    "2K",
    "BANDAI NAMCO",
    "Devolver Digital",
    "Team17",
    "Annapurna Interactive",
    "Focus Entertainment",
    "Konami",
    "Atlus",
    "CD PROJEKT RED",
    "Aspyr",
    "THQ Nordic",
    "Raw Fury",
    "Focus Home",
    "Crytek",
    "Koei Tecmo",
    "Marvelous",
    "DotEmu",
    "Tribute Games",
    "Motion Twin",
    "Playdigious",
    "Chucklefish",
    "Finji",
]
